spring:
  datasource:
    #    url: jdbc:postgresql://192.168.18.100:5432/LYDB?currentSchema=lyschema
    #    username: ly_dev
    #    password: ly_dev
    url: jdbc:postgresql://10.43.138.190:5432/postgres?currentSchema=optimistic
    username: postgres
    password: root
    driverClassName: org.postgresql.Driver
    type: com.alibaba.druid.pool.DruidDataSource


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml # 如果有Mapper XML文件的话
  type-aliases-package: org.lyflexi.debug_mybatis.entity # 实体类包路径
  global-config:
    db-config:
      logic-delete-field: data_status # 全局逻辑删除字段名
      logic-delete-value: 1 # 逻辑已删除值
      logic-not-delete-value: 0 # 逻辑未删除值

server:
  port: 8080